#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
./Allclean
runApplication  blockMesh

restore0Dir

runApplication	decomposePar

touch lagEB.foam

#-- Run in parallel
runParallel $(getApplication)

#runApplication simpleFoam

# Reconstruct
runApplication reconstructPar

