#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
./Allclean
runApplication  blockMesh

restore0Dir

touch lagEB.foam

#-- Run in parallel
runApplication $(getApplication)


